name: rest_api_client
description: Abstraction for communicating with REST API in flutter projects. Incorporates exception handling and jwt with refresh token authorization.
version: 2.3.13
# repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  storage_repository:
    path: ../storage_repository
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: '>=5.12.0 <7.0.0'
  flutter_lints: ^6.0.0


dependency_overrides:

